name: Trigger Autograding

on:
  push:
    branches:
      - main

jobs:
  trigger-autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger autograding in classroom repo
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.OSCAMP_25SP_PROJ1_STARRY_NEXT_AUTOGRADE }}" \
            https://api.github.com/repos/LearningOS/oscomp-test-elebirds/dispatches \
            -d '{"event_type":"autograde","client_payload":{"ref":"main"}}'